### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compile

### ISSUE THREAD

**Issue by GaneshShetty951** [payu-intrepos/payu-olamoney-ios#3]
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2.4 compiler: ____/PayUOlaMoneySDK.framework/Modules/PayUOlaMoneySDK.swiftmodule/x86_64-apple-ios-simulator.swiftmodule

**Comment by RajvinderPayU** [comment]
Closing this as this issue is resolved in the latest version.
